### ISSUE TITLE
Problems with initial setup

### ISSUE THREAD

**Issue by nunju9a** [treehouse-apprenticeship/athena_nj#1]
Within "Developing Without Docker" we have followed the instructions up to `run the command "mongod"`, however there is an error in the command prompt saying `C:\data\db\ not found., terminating`.  When we try to run `npm run seed` we are getting a MongoNetworkError.  Cannot move past this step. @Ark20

**Comment by MariahRojas** [comment]
Hi as per these instructions http://treehouse.github.io/installation-guides/windows/mongo-windows.html. You would need to md \data\db\
