### ISSUE TITLE
### Issue: The placeholder text for the Sign In page's "Email Address" field is misspelled

### ISSUE THREAD

**Issue by younso9** [treehouse-apprenticeship/athena_nj#5]
On the Sign In page, the placeholder text for the "Email Address" field is misspelled as "Email Addrss".

**Steps to Reproduce**

* Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.
* Notice that the placeholder text for the "Email Address" field is misspelled as "Email Addrss".

**Comment by lucco22** [comment]
Typo has been fixed.
